AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/BarePercentLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
