dist: trusty-692-1323f09
sudo: required

language: ruby
rvm:
  - 2.3.1

notifications:
  email: false

addons:
  postgresql: "9.4"

bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - psql -c 'create database questions_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:setup
  - 'bundle exec rackup -s puma -E production &'
  - sleep 3

script:
  - bundle exec rspec --tag ~visual

gemfile:
  - Gemfile
